name: barcode_finder
description: Plugin for reading barcodes from files.
version: 0.0.1
homepage: https://github.com/PopcodeMobile/barcode-finder

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.popcode.barcode_finder
        pluginClass: BarcodeFinderPlugin
      ios:
        pluginClass: SwiftBarcodeFinderPlugin